### ISSUE TITLE
Pipeline fails with "Unexpected value 'schedules'"

### ISSUE THREAD

**Issue by kylgrn** [JulianHayward/Azure-MG-Sub-Governance-Reporting#28] opened 2021-01-22 17:31 UTC
Getting the following error trying to run the pipeline: AzGovViz.yml (Line: 36, Col: 1): Unexpected value 'schedules'

**Comment by JulianHayward** [comment] 2021-01-23 12:44
the issue is related to Azure DevOps Server.
Please let us know once you found a solution.
Closing this for now.

**Closed by JulianHayward** 2021-01-23 12:44 UTC
